### ISSUE TITLE
the app installation 

### ISSUE THREAD

**Issue by Yisher** [ErikMaris/DiffusionLab#5]
sorry but I can not find the appinstall file anywhere.Are you guys sure you have publisher it in github or anywhere else?

**Comment by ErikMaris** [comment]
The installation file "DiffusionLab_v1-1-0.mlappinstall" can be downloaded [here](https://github.com/ErikMaris/DiffusionLab/releases/tag/v.1.1.0) :-).

**Comment by Yisher** [comment]
ok,thx for reply, I can't wait to try it
